spring.application.name=paww
server.port=8080
spring.datasource.url=jdbc:postgresql://ep-blue-cherry-a1sgb302-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_gmF1Td6qNwbc&sslmode=require&channelBinding=require

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

cloudinary.cloud_name=dlevbirqh
cloudinary.api_key=934746557692255
cloudinary.api_secret=hG7xFH_SsNZGs8BdZ5VY4ohVwa8